---
  - name: "Install Prometheus Server with Ansible"
    hosts: localhost
    connection: local
    tasks:

    - name: "Create the Monitoring Namespace"
      command: "kubectl apply -f /workspace/roles/monitoring/templates/prometheus-ns.yml"

    - name: "Create a clusterrole binding and rbac"
      command: "kubectl apply -f /workspace/roles/monitoring/templates/clusterrole.yml"

    - name: "Create a service account for kube-state-metrics"
      command: "kubectl apply -f /workspace/roles/monitoring/templates/kube-state-metrics-configs-service-account.yaml"

    - name: "Create a cluster role for kube-state-metrics"
      command: "kubectl apply -f /workspace/roles/monitoring/templates/kube-state-metrics-configs-cluster-role.yaml"

    - name: "Create a cluster role binding for kube-state-metrics"
      command: "kubectl apply -f /workspace/roles/monitoring/templates/kube-state-metrics-configs-cluster-role-binding.yaml"

    - name: "Create a deployment for kube-state-metrics"
      command: "kubectl apply -f /workspace/roles/monitoring/templates/kube-state-metrics-configs-deployment.yaml"

    - name: "Create a service for kube-state-metrics"
      command: "kubectl apply -f /workspace/roles/monitoring/templates/kube-state-metrics-configs-service.yaml"
      
    - name: "Create a ConfigMap for prometheus"
      command: "kubectl apply -f /workspace/roles/monitoring/templates/prometheus-configmap.yml"

    - name: "Create a deployment for prometheus"
      command: "kubectl apply -f /workspace/roles/monitoring/templates/prometheus-deployment.yml"
  
    - name: "Create a ingres resouce for prometheus"
      command: "kubectl apply -f /workspace/roles/monitoring/templates/prometheus-ingress.yaml"
