---
  - name: "Install Gitlab with Ansible"
    hosts: gitlab_server

    tasks:
    - name: "update gitlab server hostnames"
      hostname:
        name: "{{ gitlab_hostname }}"

    - name: check connection
      ping:
    
    - name: setup
      setup:
  
    - name: "Build hosts file"
      lineinfile: 
        dest: /etc/hosts
        state: present
        regexp: '.*{{ item }}$' 
        line: "{{ hostvars[item].ansible_default_ipv4.address }} {{hostvars[item].ansible_hostname}}"
      when: hostvars[item].ansible_default_ipv4.address is defined
      with_items: "{{ groups['all'] }}"

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: "Install requiered packages"
      apt:
        name:
          - wget 
          - unzip
          - policycoreutils 
          - postfix  
        state: present

    - name: "download gitlab repo script"
      get_url: 
        url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
        dest: /tmp/
        mode: "u=rwx,g=rx,o=rx"

    - name: "run gitlab repo script"
      shell: /bin/bash /tmp/script.deb.sh
  
    - name: "Install Gitlab Packages"
      apt:
        name: gitlab-ce
        state: present
 
    - name: "generate /etc/gitlab/gitlab.rb template"
      template:
        src: /workspace/roles/gitlab/templates/gitlab.rb.j2
        dest: /etc/gitlab/gitlab.rb


    - name: "reconfigure gitlab"
      shell: gitlab-ctl reconfigure

    - name: "download gitlab runner binary"
      get_url:
        url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
        dest: /usr/local/bin/gitlab-runner
        mode: "u=rwx,g=rx,o=rx"

    - name: "Create gitlab-runner user"
      user:
        name: gitlab-runner
        shell: /bin/bash
        create_home: yes

    - name: "run gitlab-runner installation"
      shell: " /usr/local/bin/gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner"

    - name: "run gitlab-runner start"
      command: "/usr/local/bin/gitlab-runner start"     
