---
  - name: "Install Alert Manager with Ansible"
    hosts: localhost
    connection: local
    vars_prompt:

    - name: alertmanagerip
      prompt: "What is your alert manager server ip? "
      private: no

    - name: alertmanagerversion
      prompt: "Which version alert manager has installing"
      private: no

    tasks:
    
    - name: "Run Alert ManagerPlaybook"
      command: ansible-playbook -i /workspace/roles/alertmanager/tasks/host.ini  --become --become-user=root /workspace/roles/alertmanager/tasks/alertmanager.yml --extra-var "alertmanagerversion={{alertmanagerversion}}"
